config/routes.rb
Rails.application.routes.draw do
  resources :authentications
  resources :friendships
  resources :view
  devise_for :users, :controllers => {registrations: 'registrations'}
	root 'messages#index'
	# get  'messages#friend'
	get 'messages' => 'messages#friend'
	# index '' =>'messages#index'
	# get '/new_user' => 'static_pages#rooe', as: :new_user
	resource :messages, only: [:create, :new, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
end

app/models/friend.rb
class Friend < ApplicationRecord
	# belongs_to :message
	belongs_to :user

	validates :user_id, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, :class_name => "User"
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :sender, class_name: 'User'
	has_many :recipients
	has_many :users, :through => :recipients

	validates :sender_id, presence: true
	validates :body, presence: true

	def user_tokens=(ids)
	    self.user_ids = ids
	end
end

app/models/recipient.rb
class Recipient < ApplicationRecord
	belongs_to :message
	belongs_to :user

	validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

	has_many :messages, foreign_key: :sender_id
	has_many :friendships
	has_many :friends, :through => :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  before_action :set_authentication, only: [:show, :edit, :update, :destroy]

  # GET /authentications
  # GET /authentications.json
  def index
    @authentications = Authentication.all
  end

  # GET /authentications/1
  # GET /authentications/1.json
  def show
  end

  # GET /authentications/new
  def new
    @authentication = Authentication.new
  end

  # GET /authentications/1/edit
  def edit
  end

  # POST /authentications
  # POST /authentications.json
  def create
    @authentication = Authentication.new(authentication_params)

    respond_to do |format|
      if @authentication.save
        format.html { redirect_to @authentication, notice: 'Authentication was successfully created.' }
        format.json { render :show, status: :created, location: @authentication }
      else
        format.html { render :new }
        format.json { render json: @authentication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authentications/1
  # PATCH/PUT /authentications/1.json
  def update
    respond_to do |format|
      if @authentication.update(authentication_params)
        format.html { redirect_to @authentication, notice: 'Authentication was successfully updated.' }
        format.json { render :show, status: :ok, location: @authentication }
      else
        format.html { render :edit }
        format.json { render json: @authentication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authentications/1
  # DELETE /authentications/1.json
  def destroy
    @authentication.destroy
    respond_to do |format|
      format.html { redirect_to authentications_url, notice: 'Authentication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authentication
      @authentication = Authentication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def authentication_params
      params.require(:authentication).permit(:user_id, :provider, :uid)
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # def current_user
  #   User.find_by id: session["current_user_id"]
  #   # or whatever
  # end
  helper_method :current_user

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.where("user_id = ?",  params[:user_id])
    @friendname = User.where(id: @friendships.map(&:friend_id)).order('id ASC')
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
    @friendships = Friendship.all

  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    # @friendship = Friendship.new(friendship_params)
    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])

     if @friendship.save
      flash[:notice] = "Added friend."
      redirect_to root_url
    else
      flash[:error] = "Unable to add friend."
      redirect_to root_url
    end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to @friendship, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id, :create, :destroy)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!
	 
	def new
		@message = Message.new
		@user = current_user.following
		@users = User.all
	end

	def create
		@message = current_user.messages.build(message_params)

		if @message.save
			flash[:success] = "Message Sent!"
			redirect_to root_path
		else
			flash[:alert] = "Great Scott!"
			render :new
		end
	end

	def index
		@messages = Recipient.where(:user_id => current_user.id).order("created_at DESC")
	end

	def new
		@message = Message.new
		# @recipients = User.all
		@friendships = Friendship.where("user_id = ?",  params[:user_id])
    	@recipients = User.where(id: @friendships.map(&:friend_id)).order('id ASC')
	end
	def friend
		@users = User.all
		@recipients = User.all
	end

	def show
		@message = Message.new
		@recipients = User.all
	end

	private

		def message_params
			params.require(:message).permit(:body, :content, :title, :thumbnail_url, :sender_id, user_tokens: [])
		end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def root
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/authentications/_form.html.erb
<%= form_for(authentication) do |f| %>
  <% if authentication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(authentication.errors.count, "error") %> prohibited this authentication from being saved:</h2>

      <ul>
      <% authentication.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :provider %>
    <%= f.text_field :provider %>
  </div>

  <div class="field">
    <%= f.label :uid %>
    <%= f.text_field :uid %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing Authentication</h1>

<%= render 'form', authentication: @authentication %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authentications</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Provider</th>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authentications.each do |authentication| %>
      <tr>
        <td><%= authentication.user_id %></td>
        <td><%= authentication.provider %></td>
        <td><%= authentication.uid %></td>
        <td><%= link_to 'Show', authentication %></td>
        <td><%= link_to 'Edit', edit_authentication_path(authentication) %></td>
        <td><%= link_to 'Destroy', authentication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Authentication', new_authentication_path %>

app/views/authentications/new.html.erb
<h1>New Authentication</h1>

<%= render 'form', authentication: @authentication %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @authentication.user_id %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @authentication.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @authentication.uid %>
</p>

<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>

app/views/friendships/_form.html.erb
<%= form_for(friendship) do |f| %>
  <% if friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :friend_id %>
    <%= f.number_field :friend_id %>
  </div>

  <div class="field">
    <%= f.label :create %>
    <%= f.text_field :create %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1 >Friendships</h1>

<table class="form-box">
  <thead>
      <th>Friend Name</th>
      <th colspan="3"></th>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.friend_id %></td>
      </tr>
    <% end %>
    <% @friendname.each do |friendname| %>
          <tr>
            <td><%= friendname.username %></td>
          </tr>
        <% end %>
  </tbody>
</table>

<br> -->

<div class="form-bigbox">
  <div class="form-box">
<div id="stream">

    <div id="stream-list" class="follow-list">
      <ul>   
        <% @friendname.each do |friendname| %>
          <label for="friendname<%= friendname.id %>" >
            <li id="stream_item">
              <span class="list-group-item"><%= friendname.username %></span>
            </li>
          </label>
          <br>
        <% end %>
      </ul>
    </div>

    <div id ="stream-footer">
    </div>
    </div>
    </div>
</div>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>


<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>

app/views/layouts/_header.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <div class="logo"><%= link_to 'Coder Chat', root_path %></div>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">Menu</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <% if user_signed_in? %>
          <li class="nav-link"><%= link_to "New", new_messages_path(:user_id => current_user.id) %></li>
          <li class="nav-link"><%= link_to "Add Friends", messages_path %></li>
          <li class="nav-link"><%= link_to "Your Friends", friendships_path(:user_id => current_user.id) %></li>
          <li class="nav-link"><%= link_to "Inbox",  root_path  %></li>
          <li class="nav-link"><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
        <% else %>
          <li class="nav-link"><%= link_to "Sign In", new_user_session_path %></li>
          <li class="nav-link"><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snapchat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

	<div class="container">
		<% flash.each do |message_type, message| %>
			<div id="flash" class="flash-<%= message_type %>"><%= message %></div>
		<% end %>

		<%= yield %>
	</div>
  </body>
</html>

app/views/messages/_friends.html.erb
<div id="stream">
<!-- 	<%= form_for :friend, url: messages_path do |f| %>

		<div id="stream-list" class="follow-list">
			<ul>   
				<% @recipients.each do |user| %>
					<label for="user<%= user.id %>" >
						<li id="stream_item">
							<span class="list-group-item"><%= user.username %></span>
							<%= check_box_tag "message[user_tokens][]", user.id, @users.include?(user), id: "user#{user.id}" %>
						</li>
					</label>
					<br>
				<% end %>
			</ul>
		</div>

		<div id ="stream-footer">
			<%= f.button :"Add Friend", class: "btn btn-outline" %>
		</div>

	<% end %> -->
	<!-- <div id="stream-list" class="follow-list">
		<ul>  
			<% for user in @users %>
				<div class="user">
					<li id="stream_item">
					<strong><%= user.username %></strong>
						<%= link_to "Add Friend", friendships_path(:user_id => user, :friend_id => user), :method => :post %>
					<div class="clear"></div>
					</li>
				</div>
			<% end %>
		</ul> -->
		</div>



<div id="stream">

    <div id="stream-list" class="follow-list">
      <ul>   
        <% for user in @users %>
          <label for="user<%= user.id %>" >
            <li id="stream_item">
              <span class="list-group-item"><%= user.username %></span>

            </li>
            <br>
            <li id="stream_item">
             <%= link_to "Add Friend", friendships_path(:user_id => user, :friend_id => user), :method => :post %>
             </li>
          </label>
          <br>
        <% end %>
      </ul>
    </div>

    <div id ="stream-footer">
    </div>
    </div>

</div>

app/views/messages/_messages.html.erb
<% @messages.each do |message| %>
  <div class="post_show">
    <div class="panel panel-default">
      <div class="panel-heading post_media">
        <% if message.message.html.present? %>
        <%= message.message.html.html_safe %>
        <% end %>
      </div>
      <div class="post-body">
        <%= message.message.content %>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="name_avatar u-pull-left">
            <span class="round-image-50 name  user_avatar u-pull-left">
            
            </span>
            <span class="user_name post_name u-pull-left">
            <%= link_to message.message.sender.name, message.message.sender %>
            </span>

          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/messages/_recipients.html.erb
<div id="stream">
	<%= form_for :message, url: messages_path do |f| %>
		<%= f.text_area :body,  id: "url", placeholder: "Message", class: "message_body" %>

		<div id="stream-list" class="follow-list">
			<ul>   
				<% @recipients.each do |user| %>
					<label for="user<%= user.id %>" >
						<li id="stream_item">
							<span class="list-group-item"><%= user.username %></span>
							<%= check_box_tag "message[user_tokens][]", user.id, @message.users.include?(user), id: "user#{user.id}" %>
						</li>
					</label>
					<br>
				<% end %>
			</ul>
		</div>

		<div id ="stream-footer">
			<%= f.button :submit, class: "btn btn-outline" %>
		</div>

	<% end %>
</div>

app/views/messages/friend.html.erb
<div class="form-bigbox">
	<div class="form-box">
		<%= render 'messages/friends' %>
	</div>
</div>

app/views/messages/index.html.erb
<div class="bigbox">
	<div class="box">
		<% @messages.each do |message| %>
			<div class="message">
				<div class="top-message">
					<li class="writing"><%= message.message.body %></li>
				</div>

				<div class="bottom-message">
					<span>From </span><%= message.message.sender.username %>
					<span> At </span><%= message.message.sender.created_at %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/messages/new.html.erb
<div class="form-bigbox">
	<div class="form-box">
		<%= render 'messages/recipients' %>
	</div>
</div>

app/views/static_pages/root.html.erb
<h1>hello</h1>	